// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBereqeSEZj3-zgjQecFHvn7E0Z7CpUPGU',
    appId: '1:131348039997:web:d7a8f1f46b9b3d65d31d54',
    messagingSenderId: '131348039997',
    projectId: 'sports-app-2542c',
    authDomain: 'sports-app-2542c.firebaseapp.com',
    storageBucket: 'sports-app-2542c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2szu0Yxk22FuvR0bSw24IWSdYTDARGCg',
    appId: '1:131348039997:android:c21ee9fd774c7e00d31d54',
    messagingSenderId: '131348039997',
    projectId: 'sports-app-2542c',
    storageBucket: 'sports-app-2542c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjrJUjCr61lpEf7TXxvy4HtaSDzzZnoxI',
    appId: '1:131348039997:ios:8d340050aa584f50d31d54',
    messagingSenderId: '131348039997',
    projectId: 'sports-app-2542c',
    storageBucket: 'sports-app-2542c.appspot.com',
    iosClientId: '131348039997-gksnsk96ppi5dbf0ecfp7fehr078e55d.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjrJUjCr61lpEf7TXxvy4HtaSDzzZnoxI',
    appId: '1:131348039997:ios:65d444d9a8f64707d31d54',
    messagingSenderId: '131348039997',
    projectId: 'sports-app-2542c',
    storageBucket: 'sports-app-2542c.appspot.com',
    iosClientId: '131348039997-u4e6baommd8997o2hcvbtkctsjrrg95t.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsApp.RunnerTests',
  );
}
